dist: trusty
language: python
python:
  - "2.7"
  - "3.5"
before_install:
  - sudo add-apt-repository ppa:teward/swig3.0 -y
  - sudo apt-get update -qq
  - sudo apt-get install -y swig3.0
  - sudo apt-get install -y libcoin80
  - sudo apt-get install -y libcoin80-dev

install:
  - python setup.py install

script:
  - python tests/coin_tests.py

branches:
  only:
    - master