package:
  name: pivy
  version: 0.6.0

build:
  number: 4

source:
  path: ../../

requirements:
  build:
    - python
    - swig
    - coin
  run:
    - python
    - coin

about:
  summary: python buindings to coin